openapi: 3.0.2
info:
  version: "1.0.0"
  title: "Ruralis"

servers:
  - url: http://localhost:5000

paths:
  /api/public/game:
    post:
      summary: Create a game of Ruralis
      security: []   # No security
      tags:
        - games
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scenario:
                  type: integer
                players:
                  type: array
                  items:
                    type: integer


      responses:
        '201':
          description: Create successfull
